### ISSUE TITLE
Not working on Nuxt

### ISSUE THREAD

**Issue by vickykeen** [heidkaemper/tailwindcss-intersect#1]
Hi Thank you for this,
May i know this is not working in Nuxt

**Comment by heidkaemper** [comment]
This should be fixed with release 1.0.2:
https://github.com/heidkaemper/tailwindcss-intersect/releases/tag/1.0.2

If there are still problems with Nuxt.js, please let me know.

**Comment by vickykeen** [comment]
Thank you very will try it out and let you know.
