### ISSUE TITLE
Using with @layer/@apply directives

### ISSUE THREAD

**Issue by divan** [heidkaemper/tailwindcss-intersect#3]
Hi, it's handy to create own @layer directives for the common usages of `intersect:`.

So instead of writing long strings like 'translate-x-1/4 intersect:translate-x-0 transition ease-out duration-800` over and over, with @apply it would be something like `animate-left`.

Example:
```
@layer utilities {
    .animate-left {
        @apply translate-x-1/4 intersect:translate-x-0 transition ease-out duration-800;
    }
}
```

But it doesn't seem to work. Looks like @layer directive doesn't handle `intersect:`. I have no knowledge of the Tailwind internals, so don't know if it's my mistake or a framework inconsistency.

Any ideas how to make it work?

**Comment by divan** [comment]
@heidkaemper thanks for the explaining! I think the second one looks simpler (but isn't it breaking the APi of this package?).

**Comment by heidkaemper** [comment]
Okay, I should have said weeks not days.. :-)

With version 1.0.4 comes the ability to use custom classes. That should work for your example.
https://github.com/heidkaemper/tailwindcss-intersect#custom-classes

Side node: Another great option to achieve something like this is to use CSS animations instead fo transitions. You could define your own or use a package like Tailwind CSS Animated:
https://www.tailwindcss-animated.com/

The following example should work nicely:
`<div class="intersect:animate-fade-left"></div>`
