### ISSUE TITLE
Observer.start() does not work with NextJS + Tailwind

### ISSUE THREAD

**Issue by yev-yev-yev** [heidkaemper/tailwindcss-intersect#6]
`Observer.observe();` does work. Is that a safe approach. Working code:

```
 const intersectionObserverStarted = useRef<boolean>(false);

  useEffect(() => {
    if (!intersectionObserverStarted.current) {
      intersectionObserverStarted.current = true;
      IntersectionObserver.observe();
    }
  }, []);
```

package.json
```
    "react": "18.2.0",
    "next": "13.1.1",
    "postcss": "8.4.20",
    "tailwindcss": "3.2.4",
    "tailwindcss-intersect": "1.0.3"
```

**Comment by yev-yev-yev** [comment]
Seems related to the DOMContentLoaded event with NextJs - https://github.com/vercel/next.js/discussions/36622

**Comment by heidkaemper** [comment]
Hi Yev.

I have to admit, I don't really get the problem here.. :-)

Why do you have to call the `observe()` method instead of `start()`?
Does IntersectionObserver.start() not work in an NextJS environment?

**Comment by yev-yev-yev** [comment]
That's correct, `start()` does not work. It doesn't throw any errors. I believe the issue is related to the timing of the `DOMContentLoaded` event or `document.readyState`

**Comment by heidkaemper** [comment]
This should FINALLY be fixed with v2.0.1 🎉

At least it works for me in a Next.js 14 setup now. Depending on the type of your component, `Observer.start()` may need to be called in an useEffect hook.

```
useEffect(() => {
  Observer.start()
}, []);
```

https://github.com/heidkaemper/tailwindcss-intersect/releases/tag/v2.0.1

**Comment by mochetts** [comment]
Not working for me. Had to add a timeout to do `Observer.start()` after some milliseconds. I basically need to let the renderer render all the classes.

**Comment by Zefty** [comment]
How can i use this in a server component?
